import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api.ts"

const AllMyNotes: NextPage = () => {
  const utils = api.useContext()
  const { data: Allnotes, isLoading } = api.mynotes?.allNotes.useQuery()
  
  const deleteSingleNote = api.mynotes.deleteNode.useMutation({
    onMutate: () => {
      utils.mynotes.allNotes.cancel()
      const optimisticUpdate = utils.mynotes.allNotes.getData()

      if (optimisticUpdate) {
        utils.mynotes.allNotes.setData(optimisticUpdate)
      }
    },
    onSettled: () => {
      utils.mynotes.allNotes.invalidate()
    }
  })

  if (isLoading) return <>Loading...</>

  return (
    <>
      {Allnotes?.map((note, index) => (
        <div key={index} className="border border-gray-100 px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href={`/${note.id}`}>
              <h5 className="text-1xl font-bold">{note.title}</h5>
            </Link>
            <div className="flex gap-3">
              <div>
                <Link href={`editnote/${note.id}`}>
                  edit
                </Link>
              </div>
              <div onClick={() => deleteSingleNote.mutate({
                id: note.id
              })}>
                delete
              </div>
            </div>
          </div>
        </div>
      ))}
    </>
  )
}

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="container mt-6 mx-auto">
        <div className="flex justify-between items-center">
          <h1>List of al notes</h1>
          <Link 
            className="inline-block rounded-lg bg-green-600 px-4 py-1.5 text-base font-semibold leading-7 text-white shadow-sm ring-1 ring-green-600 hover:bg-green-700 hover:ring-green-700"
            href="/newnote"
          >
            Add a note 
          </Link>
        </div> 
        <div className="mt-6">
          <AllMyNotes />
        </div>
     </main>
    </>
  );
};

export default Home;
